export const apiEndPoint = {
    CATEGORY_API: "/category/list",
    STATE_API: "/state/findState",
    TOP_PRODUCT_API: "/book/topBooks",
    CITY_API: "/city/cityByState",
    VERIFY_API: "/user/verifyEmail",
    FREE_BOOK_API: "/book/freebooklist",
    BOOK_BY_CATEGORY: "/book/searchByCategoryId",
    USER_SIGNIN: "/user/signIn",
    USER_SIGNUP: "/user/signup",
    USER_UPDATEPROFILE: "/user/updateProfile",
    Search_By_Categoryname: "/book/searchByCategoryId",
    Search_by_Other: "/book/searchbyAuthor",
    All_Books: "/book/list",
    RECENT_PRODUCT: '/product/recent-product',
    PRODUCT_LIST: '/product/list',
    FETCH_CART: '/cart/fetchCart',
    ADD_TO_CART: '/cart/addToCart',
    USER_CART : "/cart/userCart",
    ADD_BOOK : "/book/add",
    SEARCH_BOOKS : "/book/searchByKeyword"
}
